# Generated by Django 3.0.2 on 2020-06-08 19:09

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='知识模块')),
                ('order_num', models.IntegerField(default=10000, verbose_name='排序值[越小越靠前]')),
            ],
            options={
                'verbose_name': '知识模块',
                'verbose_name_plural': '知识模块',
                'db_table': 'cms_chapter',
                'ordering': ['course', 'order_num', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='项目编号')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '培训课程',
                'verbose_name_plural': '培训课程',
                'db_table': 'cms_course',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=600, verbose_name='标题')),
                ('choices', django_extensions.db.fields.json.JSONField(default=dict, verbose_name='选择内容')),
                ('answers', django_extensions.db.fields.json.JSONField(default='[]', verbose_name='答案')),
                ('qtype', models.SmallIntegerField(blank=True, choices=[(0, '单选题'), (1, '判断题'), (2, '多选题')], default=0, verbose_name='题目类型')),
                ('order_num', models.IntegerField(default=100000, verbose_name='排序值[越小越靠前]')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Chapter', verbose_name='所属章节')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'cms_question',
                'ordering': ['course', 'order_num', 'id'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Course', verbose_name='所属项目'),
        ),
    ]
